import { Router } from 'express';
import prisma from '../lib/prisma.js';
import { AUDIT } from '../lib/constants.js';
import { logAudit } from '../lib/audit.js';
import { requireAuth, can, assertVisible } from '../middleware/auth.js';
import { asyncHandler, HttpError } from '../middleware/error.js';
import { monthRange, currentMonth } from '../lib/dates.js';
import { computeSalary } from '../services/salary.js';
import { buildReportHtml } from '../services/reportHtml.js';
import { computeAutoHealth, resolveHealth } from '../services/health.js';

/**
 * One employee, one month, everything on record — weekly reports, daily work,
 * attendance, tasks and the pay that came out of it.
 *
 * Delivered as a single CSV with a labelled section per topic rather than five
 * separate downloads. Somebody reviewing an employee wants one file they can
 * open in Excel and scroll, and each section keeps its own column headings so
 * the mixed widths still read correctly.
 */
const router = Router();
router.use(requireAuth);

const escape = (v) => `"${String(v ?? '').replace(/"/g, '""')}"`;
const row = (values) => values.map(escape).join(',');
const blank = '';

router.get(
  '/employee/:userId',
  asyncHandler(async (req, res) => {
    // An employee may always pull their own month; anyone else needs to be
    // allowed to look at work in the first place.
    const own = req.params.userId === req.user.id;
    if (!own && !can(req.user, 'work.view')) throw new HttpError(403, 'Not allowed');

    const month = /^\d{4}-\d{2}$/.test(String(req.query.month || ''))
      ? String(req.query.month)
      : currentMonth();
    const { start, end } = monthRange(month);

    const user = await prisma.user.findUnique({
      where: { id: req.params.userId },
      include: { department: true, jobRoles: { include: { jobRole: true } } },
    });
    assertVisible(req.user, user);

    const [weekly, work, attendance, tasks, leaves] = await Promise.all([
      prisma.weeklyReport.findMany({
        where: { userId: user.id, weekStart: { gte: start, lte: end } },
        orderBy: { weekStart: 'asc' },
      }),
      prisma.workSubmission.findMany({
        where: { userId: user.id, date: { gte: start, lte: end } },
        include: {
          entries: { include: { question: true } },
          reviewedBy: { select: { name: true } },
        },
        orderBy: { date: 'asc' },
      }),
      prisma.attendance.findMany({
        where: { userId: user.id, date: { gte: start, lte: end } },
        orderBy: { date: 'asc' },
      }),
      prisma.taskResponse.findMany({
        where: { userId: user.id, createdAt: { gte: new Date(`${start}T00:00:00`), lte: new Date(`${end}T23:59:59`) } },
        include: { task: true, reviewedBy: { select: { name: true } } },
        orderBy: { createdAt: 'asc' },
      }),
      prisma.leaveRequest.findMany({
        where: { userId: user.id, fromDate: { lte: end }, toDate: { gte: start } },
        include: { reviewedBy: { select: { name: true } } },
        orderBy: { fromDate: 'asc' },
      }),
    ]);

    // Pay is only included for someone allowed to see pay at all.
    const salary = can(req.user, 'salary.view') ? await computeSalary(user.id, month) : null;

    // The health scorecard, resolved for the same month.
    const healthReport = await prisma.healthReport.findUnique({
      where: { userId_month: { userId: user.id, month } },
    });
    const health = resolveHealth(healthReport, await computeAutoHealth(user.id, month));

    // The document is the default. CSV stays for anyone feeding a spreadsheet.
    if (req.query.format !== 'csv') {
      const logoRow = await prisma.setting.findUnique({ where: { key: 'branding.logo' } });
      const html = buildReportHtml({
        user,
        month,
        logo: logoRow?.value ?? null,
        weekly,
        work,
        attendance,
        leaves,
        tasks,
        salary,
        health,
        generatedBy: req.user.name,
      });

      await logAudit(
        req.user,
        AUDIT.REPORT_EXPORTED,
        'User',
        user.id,
        `Opened the full ${month} report for ${user.name}`
      );

      res.setHeader('Content-Type', 'text/html; charset=utf-8');
      return res.send(html);
    }

    const lines = [
      row(['Full report']),
      row(['Employee', `${user.name} (${user.employeeId})`]),
      row(['Department', user.department?.name ?? '-']),
      row(['Job roles', user.jobRoles.map((j) => j.jobRole?.name).filter(Boolean).join(' / ') || '-']),
      row(['Month', month]),
      row(['Generated', new Date().toISOString()]),
      row(['Generated by', req.user.name]),
      blank,

      row(['WEEKLY REPORTS']),
      row([
        'Week of', 'Tasks assigned', 'Tasks completed', 'Pending & reason',
        'Key achievement', 'Challenges', 'Next week plan', 'Support required', 'Submitted',
      ]),
      ...(weekly.length
        ? weekly.map((w) =>
            row([
              w.weekStart, w.tasksAssigned, w.tasksCompleted, w.pendingTasks,
              w.keyAchievement, w.challenges, w.nextWeekPlan, w.supportRequired,
              w.submittedAt.toISOString(),
            ])
          )
        : [row(['No weekly reports submitted this month'])]),
      blank,

      row(['DAILY WORK']),
      row(['Date', 'Status', 'Total units', 'What was done', 'Note from employee', 'Reviewed by', 'Rejection reason']),
      ...(work.length
        ? work.map((s) =>
            row([
              s.date,
              s.status,
              s.entries.reduce((sum, e) => sum + e.value, 0),
              s.entries.map((e) => `${e.question?.label}: ${e.value}${e.failedValue ? ` (${e.failedValue} failed)` : ''}`).join('; '),
              s.note,
              s.reviewedBy?.name,
              s.rejectionReason,
            ])
          )
        : [row(['No work submitted this month'])]),
      blank,

      row(['ATTENDANCE']),
      row(['Date', 'Status', 'In', 'Out', 'Hours', 'Late minutes', 'Note']),
      ...(attendance.length
        ? attendance.map((a) =>
            row([
              a.date, a.status,
              a.checkIn?.toISOString() ?? '', a.checkOut?.toISOString() ?? '',
              a.hours, a.lateMinutes ?? '', a.note,
            ])
          )
        : [row(['No attendance recorded this month'])]),
      blank,

      row(['LEAVE']),
      row(['From', 'To', 'Type', 'Status', 'Paid', 'Reason', 'Decided by', 'Note']),
      ...(leaves.length
        ? leaves.map((l) =>
            row([
              l.fromDate, l.toDate, l.type, l.status,
              l.isPaid === null ? '' : l.isPaid ? 'Paid (deducted)' : 'Unpaid (no deduction)',
              l.reason, l.reviewedBy?.name, l.reviewNote,
            ])
          )
        : [row(['No leave this month'])]),
      blank,

      row(['TASKS']),
      row(['Task', 'Response', 'On time', 'Status', 'Note', 'Reviewed by', 'Responded']),
      ...(tasks.length
        ? tasks.map((t) =>
            row([
              t.task?.title, t.response, t.onTime ? 'Yes' : 'No', t.status,
              t.note, t.reviewedBy?.name, t.createdAt.toISOString(),
            ])
          )
        : [row(['No task responses this month'])]),
    ];

    if (salary) {
      lines.push(
        blank,
        row(['PAY']),
        row(['Gross', salary.gross]),
        row(['Paid days', `${salary.paidDays} of ${salary.daysInMonth}`]),
        row(['Absent days', salary.absentDays]),
        row(['Half days', salary.halfDays]),
        row(['Leave charged', salary.chargedLeaveDays]),
        row(['Late days', `${salary.finedLateDays} fined of ${salary.lateDays}`]),
        row(['Deduction - absence', salary.deductions.absent]),
        row(['Deduction - half days', salary.deductions.halfDay]),
        row(['Deduction - leave', salary.deductions.chargedLeave]),
        row(['Deduction - late fine', salary.deductions.lateFine]),
        row(['Deduction - half day fine', salary.deductions.halfDayFine]),
        row(['Deduction - other', salary.deductions.manual]),
        row(['Incentive', salary.incentive]),
        row(['Bonus', salary.bonus]),
        row(['Net payable', salary.net]),
        row(['Days not yet synced', `${salary.naDays} (nothing deducted for these)`])
      );
    }

    await logAudit(
      req.user,
      AUDIT.REPORT_EXPORTED,
      'User',
      user.id,
      `Downloaded the full ${month} report for ${user.name}`
    );

    const filename = `${user.employeeId}-${month}-full-report.csv`;
    res.setHeader('Content-Type', 'text/csv; charset=utf-8');
    res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);
    res.send(`﻿${lines.join('\r\n')}`);
  })
);

export default router;
